name: headscalemanager
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.3.0+83

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI & UX
  eva_icons_flutter: ^3.1.0
  fl_chart: ^1.1.1
  graphview: ^1.5.1
  flutter_speed_dial: ^7.0.0
  curved_navigation_bar: ^1.0.6
  
  # Functionality
  http: ^1.6.0
  provider: ^6.1.5+1
  flutter_secure_storage: ^9.2.4
  qr_flutter: ^4.1.0
  url_launcher: ^6.3.2
  share_plus: ^12.0.1
  path_provider: ^2.1.1
  dart_ping: ^9.0.1
  flutter_local_notifications: ^19.5.0
  workmanager: ^0.9.0
  shared_preferences: ^2.2.3


  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7
  local_auth: ^3.0.0
  crypto: ^3.0.7
  uuid: ^4.5.2
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

dependency_overrides:
  vector_math: ^2.2.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icon/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icon/icon.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/icon/splash.png
  android: true
  ios: true
  web: false

flutter:
  uses-material-design: true
